### ISSUE TITLE
Frontend build fails because of broken file paths

### ISSUE THREAD

**Issue by terrameijar** [HashMap-ZW/parlor#7]
The CD step fails to deploy this code due to broken file paths. @Technocoder7 would you like to work on this?

![image](https://github.com/user-attachments/assets/b1757079-32f2-408e-b5dd-0f4fb08a0403)

**Comment by Technocoder7** [comment]
Sure, I ddn't have zesa. Let me fix

**Comment by terrameijar** [comment]
This was resolved in #12 . Thanks @Technocoder7 !
